// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HSG\HSG_IP_src_FIFOLF_block.v
// Created: 2018-10-21 17:42:58
// 
// Generated by MATLAB 9.3 and HDL Coder 3.11
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HSG_IP_src_FIFOLF_block
// Source Path: HSG/HSG/Edge Detector/LineBuffer/DataMemory/FIFOLF
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HSG_IP_src_FIFOLF_block
          (clk,
           reset,
           enb,
           LineIn,
           Push,
           Pop,
           load,
           LineOut);


  input   clk;
  input   reset;
  input   enb;
  input   LineIn;
  input   Push;
  input   Pop;
  input   load;
  output  LineOut;

  reg [9:0] writePointer;  // ufix10
  wire popValid;
  reg [9:0] readPointer;  // ufix10
  wire relop_relop1;
  wire notEmpty;
  reg  popValidREG;
  wire initData;
  reg  LineOut_1;


  // Free running, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  always @(posedge clk or posedge reset)
    begin : counter_process
      if (reset == 1'b1) begin
        writePointer <= 10'b0000000000;
      end
      else begin
        if (enb) begin
          if (load == 1'b1) begin
            writePointer <= 10'b0000000000;
          end
          else if (Push == 1'b1) begin
            writePointer <= writePointer + 10'b0000000001;
          end
        end
      end
    end



  // Free running, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  always @(posedge clk or posedge reset)
    begin : counter_1_process
      if (reset == 1'b1) begin
        readPointer <= 10'b0000000000;
      end
      else begin
        if (enb) begin
          if (load == 1'b1) begin
            readPointer <= 10'b0000000000;
          end
          else if (popValid == 1'b1) begin
            readPointer <= readPointer + 10'b0000000001;
          end
        end
      end
    end



  assign relop_relop1 = writePointer == readPointer;



  assign notEmpty =  ~ relop_relop1;



  assign popValid = notEmpty & Pop;



  always @(posedge clk or posedge reset)
    begin : reg_rsvd_process
      if (reset == 1'b1) begin
        popValidREG <= 1'b0;
      end
      else begin
        if (enb) begin
          popValidREG <= popValid;
        end
      end
    end



  HSG_IP_src_SimpleDualPortRAM_singlebit #(.AddrWidth(10),
                                           .DataWidth(1)
                                           )
                                         u_simpleDualPortRam (.clk(clk),
                                                              .enb(enb),
                                                              .wr_din(LineIn),
                                                              .wr_addr(writePointer),
                                                              .wr_en(Push),
                                                              .rd_addr(readPointer),
                                                              .rd_dout(initData)
                                                              );

  always @(posedge clk or posedge reset)
    begin : reg_rsvd_1_process
      if (reset == 1'b1) begin
        LineOut_1 <= 1'b0;
      end
      else begin
        if (enb && popValidREG) begin
          LineOut_1 <= initData;
        end
      end
    end



  assign LineOut = LineOut_1;

endmodule  // HSG_IP_src_FIFOLF_block

