-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Disparity_CT\Disparity_ip_src_DisparityCT.vhd
-- Created: 2021-04-24 14:26:20
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- frameOut                      ce_out        1
-- ctrlOut_hStart                ce_out        1
-- ctrlOut_hEnd                  ce_out        1
-- ctrlOut_vStart                ce_out        1
-- ctrlOut_vEnd                  ce_out        1
-- ctrlOut_valid                 ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Disparity_ip_src_DisparityCT
-- Source Path: Disparity_CT/DisparityCT
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Disparity_ip_src_DisparityCT_pkg.ALL;

ENTITY Disparity_ip_src_DisparityCT IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        RGB                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ctrl_hStart                       :   IN    std_logic;
        ctrl_hEnd                         :   IN    std_logic;
        ctrl_vStart                       :   IN    std_logic;
        ctrl_vEnd                         :   IN    std_logic;
        ctrl_valid                        :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        frameOut                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        ctrlOut_hStart                    :   OUT   std_logic;
        ctrlOut_hEnd                      :   OUT   std_logic;
        ctrlOut_vStart                    :   OUT   std_logic;
        ctrlOut_vEnd                      :   OUT   std_logic;
        ctrlOut_valid                     :   OUT   std_logic
        );
END Disparity_ip_src_DisparityCT;


ARCHITECTURE rtl OF Disparity_ip_src_DisparityCT IS

  -- Component Declarations
  COMPONENT Disparity_ip_src_RGB2Vector
    PORT( RGB                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          RGBVector                       :   OUT   vector_of_std_logic_vector8(0 TO 2)  -- uint8 [3]
          );
  END COMPONENT;

  COMPONENT Disparity_ip_src_CensusTransform
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          pixelIn                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Enable                          :   IN    std_logic;
          CTout                           :   OUT   std_logic_vector(30 DOWNTO 0)  -- ufix31
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Disparity_ip_src_RGB2Vector
    USE ENTITY work.Disparity_ip_src_RGB2Vector(rtl);

  FOR ALL : Disparity_ip_src_CensusTransform
    USE ENTITY work.Disparity_ip_src_CensusTransform(rtl);

  -- Signals
  SIGNAL RGB2Vector_out1                  : vector_of_std_logic_vector8(0 TO 2);  -- ufix8 [3]
  SIGNAL valid                            : std_logic;
  SIGNAL FF_out1                          : std_logic;
  SIGNAL CensusTransform_out1             : std_logic_vector(30 DOWNTO 0);  -- ufix31
  SIGNAL CensusTransform_out1_unsigned    : unsigned(30 DOWNTO 0);  -- ufix31
  SIGNAL Bit_Concat_out1                  : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  u_RGB2Vector : Disparity_ip_src_RGB2Vector
    PORT MAP( RGB => RGB,  -- uint32
              RGBVector => RGB2Vector_out1  -- uint8 [3]
              );

  u_CensusTransform : Disparity_ip_src_CensusTransform
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              pixelIn => RGB2Vector_out1(0),  -- uint8
              Enable => valid,
              CTout => CensusTransform_out1  -- ufix31
              );

  valid <= ctrl_valid;

  FF_out1 <= '1';

  CensusTransform_out1_unsigned <= unsigned(CensusTransform_out1);

  Bit_Concat_out1 <= FF_out1 & CensusTransform_out1_unsigned;

  frameOut <= std_logic_vector(Bit_Concat_out1);

  ce_out <= clk_enable;

  ctrlOut_hStart <= ctrl_hStart;

  ctrlOut_hEnd <= ctrl_hEnd;

  ctrlOut_vStart <= ctrl_vStart;

  ctrlOut_vEnd <= ctrl_vEnd;

  ctrlOut_valid <= ctrl_valid;

END rtl;

