-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Disparity_CT\Disparity_ip_dut.vhd
-- Created: 2021-04-24 14:26:39
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Disparity_ip_dut
-- Source Path: Disparity_ip/Disparity_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Disparity_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        RGB                               :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ctrl_hStart                       :   IN    std_logic;  -- ufix1
        ctrl_hEnd                         :   IN    std_logic;  -- ufix1
        ctrl_vStart                       :   IN    std_logic;  -- ufix1
        ctrl_vEnd                         :   IN    std_logic;  -- ufix1
        ctrl_valid                        :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        frameOut                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        ctrlOut_hStart                    :   OUT   std_logic;  -- ufix1
        ctrlOut_hEnd                      :   OUT   std_logic;  -- ufix1
        ctrlOut_vStart                    :   OUT   std_logic;  -- ufix1
        ctrlOut_vEnd                      :   OUT   std_logic;  -- ufix1
        ctrlOut_valid                     :   OUT   std_logic  -- ufix1
        );
END Disparity_ip_dut;


ARCHITECTURE rtl OF Disparity_ip_dut IS

  -- Component Declarations
  COMPONENT Disparity_ip_src_DisparityCT
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          RGB                             :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ctrl_hStart                     :   IN    std_logic;  -- ufix1
          ctrl_hEnd                       :   IN    std_logic;  -- ufix1
          ctrl_vStart                     :   IN    std_logic;  -- ufix1
          ctrl_vEnd                       :   IN    std_logic;  -- ufix1
          ctrl_valid                      :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          frameOut                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          ctrlOut_hStart                  :   OUT   std_logic;  -- ufix1
          ctrlOut_hEnd                    :   OUT   std_logic;  -- ufix1
          ctrlOut_vStart                  :   OUT   std_logic;  -- ufix1
          ctrlOut_vEnd                    :   OUT   std_logic;  -- ufix1
          ctrlOut_valid                   :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Disparity_ip_src_DisparityCT
    USE ENTITY work.Disparity_ip_src_DisparityCT(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL ctrl_hStart_sig                  : std_logic;  -- ufix1
  SIGNAL ctrl_hEnd_sig                    : std_logic;  -- ufix1
  SIGNAL ctrl_vStart_sig                  : std_logic;  -- ufix1
  SIGNAL ctrl_vEnd_sig                    : std_logic;  -- ufix1
  SIGNAL ctrl_valid_sig                   : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL frameOut_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL ctrlOut_hStart_sig               : std_logic;  -- ufix1
  SIGNAL ctrlOut_hEnd_sig                 : std_logic;  -- ufix1
  SIGNAL ctrlOut_vStart_sig               : std_logic;  -- ufix1
  SIGNAL ctrlOut_vEnd_sig                 : std_logic;  -- ufix1
  SIGNAL ctrlOut_valid_sig                : std_logic;  -- ufix1

BEGIN
  u_Disparity_ip_src_DisparityCT : Disparity_ip_src_DisparityCT
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              RGB => RGB,  -- ufix32
              ctrl_hStart => ctrl_hStart_sig,  -- ufix1
              ctrl_hEnd => ctrl_hEnd_sig,  -- ufix1
              ctrl_vStart => ctrl_vStart_sig,  -- ufix1
              ctrl_vEnd => ctrl_vEnd_sig,  -- ufix1
              ctrl_valid => ctrl_valid_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              frameOut => frameOut_sig,  -- ufix32
              ctrlOut_hStart => ctrlOut_hStart_sig,  -- ufix1
              ctrlOut_hEnd => ctrlOut_hEnd_sig,  -- ufix1
              ctrlOut_vStart => ctrlOut_vStart_sig,  -- ufix1
              ctrlOut_vEnd => ctrlOut_vEnd_sig,  -- ufix1
              ctrlOut_valid => ctrlOut_valid_sig  -- ufix1
              );

  ctrl_hStart_sig <= ctrl_hStart;

  ctrl_hEnd_sig <= ctrl_hEnd;

  ctrl_vStart_sig <= ctrl_vStart;

  ctrl_vEnd_sig <= ctrl_vEnd;

  ctrl_valid_sig <= ctrl_valid;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  frameOut <= frameOut_sig;

  ctrlOut_hStart <= ctrlOut_hStart_sig;

  ctrlOut_hEnd <= ctrlOut_hEnd_sig;

  ctrlOut_vStart <= ctrlOut_vStart_sig;

  ctrlOut_vEnd <= ctrlOut_vEnd_sig;

  ctrlOut_valid <= ctrlOut_valid_sig;

END rtl;

