-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Disparity_CT\Disparity_ip_src_RGB2Vector.vhd
-- Created: 2021-04-24 14:26:20
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Disparity_ip_src_RGB2Vector
-- Source Path: Disparity_CT/DisparityCT/RGB2Vector
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Disparity_ip_src_DisparityCT_pkg.ALL;

ENTITY Disparity_ip_src_RGB2Vector IS
  PORT( RGB                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        RGBVector                         :   OUT   vector_of_std_logic_vector8(0 TO 2)  -- uint8 [3]
        );
END Disparity_ip_src_RGB2Vector;


ARCHITECTURE rtl OF Disparity_ip_src_RGB2Vector IS

  -- Signals
  SIGNAL RGB_unsigned                     : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Bit_Slice_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Bit_Slice1_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Bit_Slice2_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Mux_out1                         : vector_of_unsigned8(0 TO 2);  -- uint8 [3]

BEGIN
  -- RGB represented in
  -- 32'hFFRRGGBB

  RGB_unsigned <= unsigned(RGB);

  Bit_Slice_out1 <= RGB_unsigned(23 DOWNTO 16);

  Bit_Slice1_out1 <= RGB_unsigned(15 DOWNTO 8);

  Bit_Slice2_out1 <= RGB_unsigned(7 DOWNTO 0);

  Mux_out1(0) <= Bit_Slice_out1;
  Mux_out1(1) <= Bit_Slice1_out1;
  Mux_out1(2) <= Bit_Slice2_out1;

  outputgen: FOR k IN 0 TO 2 GENERATE
    RGBVector(k) <= std_logic_vector(Mux_out1(k));
  END GENERATE;

END rtl;

