// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HSG\HSG_IP_src_FIFOLineStart_block1.v
// Created: 2018-10-21 17:42:58
// 
// Generated by MATLAB 9.3 and HDL Coder 3.11
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HSG_IP_src_FIFOLineStart_block1
// Source Path: HSG/HSG/Image Filter1/LineBuffer/DataMemory/FIFOLineStart
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HSG_IP_src_FIFOLineStart_block1
          (clk,
           reset,
           enb,
           lineFlag,
           load,
           pop,
           isLineStart);


  input   clk;
  input   reset;
  input   enb;
  input   lineFlag;
  input   load;
  input   pop;
  output  isLineStart;

  reg  PrevLineFlag;
  wire relop_relop1;


  always @(posedge clk or posedge reset)
    begin : reg_rsvd_process
      if (reset == 1'b1) begin
        PrevLineFlag <= 1'b0;
      end
      else begin
        if (enb && pop) begin
          PrevLineFlag <= lineFlag;
        end
      end
    end



  assign relop_relop1 = lineFlag != PrevLineFlag;



  assign isLineStart = relop_relop1;

endmodule  // HSG_IP_src_FIFOLineStart_block1

