// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\SGBMDisparity\SGBMHDLAl_ip_src_pixelBusGenerator_block6.v
// Created: 2021-04-19 19:46:15
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SGBMHDLAl_ip_src_pixelBusGenerator_block6
// Source Path: SGBMDisparity/SGBMHDLAlgorithm/SGBMHDLAlgorithmWorker/MatchingCost/HammDistRL/pixelBusGenerator
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SGBMHDLAl_ip_src_pixelBusGenerator_block6
          (clk,
           reset,
           enb,
           validIn,
           busOut_hStart,
           busOut_hEnd,
           busOut_vStart,
           busOut_vEnd,
           busOut_valid);


  input   clk;
  input   reset;
  input   enb;
  input   validIn;
  output  busOut_hStart;
  output  busOut_hEnd;
  output  busOut_vStart;
  output  busOut_vEnd;
  output  busOut_valid;


  reg [9:0] Horizontal_out1;  // ufix10
  wire hStart_out1;
  wire Logical_Operator3_out1;
  wire hEnd_out1;
  wire Logical_Operator4_out1;
  reg [18:0] Vertical_out1;  // ufix19
  wire vStart_out1;
  wire Logical_Operator5_out1;
  wire vEnd_out1;
  wire Logical_Operator6_out1;
  wire Pixel_Control_Bus_Creator_out1_hStart;
  wire Pixel_Control_Bus_Creator_out1_hEnd;
  wire Pixel_Control_Bus_Creator_out1_vStart;
  wire Pixel_Control_Bus_Creator_out1_vEnd;
  wire Pixel_Control_Bus_Creator_out1_valid;


  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 623
  always @(posedge clk or posedge reset)
    begin : Horizontal_process
      if (reset == 1'b1) begin
        Horizontal_out1 <= 10'b0000000000;
      end
      else begin
        if (enb) begin
          if (validIn == 1'b1) begin
            if (Horizontal_out1 >= 10'b1001101111) begin
              Horizontal_out1 <= 10'b0000000000;
            end
            else begin
              Horizontal_out1 <= Horizontal_out1 + 10'b0000000001;
            end
          end
        end
      end
    end



  assign hStart_out1 = Horizontal_out1 == 10'b0000000000;



  assign Logical_Operator3_out1 = validIn & hStart_out1;



  assign hEnd_out1 = Horizontal_out1 == 10'b1001101111;



  assign Logical_Operator4_out1 = validIn & hEnd_out1;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 299519
  always @(posedge clk or posedge reset)
    begin : Vertical_process
      if (reset == 1'b1) begin
        Vertical_out1 <= 19'b0000000000000000000;
      end
      else begin
        if (enb) begin
          if (validIn == 1'b1) begin
            if (Vertical_out1 >= 19'b1001001000111111111) begin
              Vertical_out1 <= 19'b0000000000000000000;
            end
            else begin
              Vertical_out1 <= Vertical_out1 + 19'b0000000000000000001;
            end
          end
        end
      end
    end



  assign vStart_out1 = Vertical_out1 == 19'b0000000000000000000;



  assign Logical_Operator5_out1 = validIn & vStart_out1;



  assign vEnd_out1 = Vertical_out1 == 19'b1001001000111111111;



  assign Logical_Operator6_out1 = validIn & vEnd_out1;



  SGBMHDLAl_ip_src_Pixel_Control_Bus_Creator_block6 u_Pixel_Control_Bus_Creator (.In1(Logical_Operator3_out1),
                                                                                 .In2(Logical_Operator4_out1),
                                                                                 .In3(Logical_Operator5_out1),
                                                                                 .In4(Logical_Operator6_out1),
                                                                                 .In5(validIn),
                                                                                 .Out1_hStart(Pixel_Control_Bus_Creator_out1_hStart),
                                                                                 .Out1_hEnd(Pixel_Control_Bus_Creator_out1_hEnd),
                                                                                 .Out1_vStart(Pixel_Control_Bus_Creator_out1_vStart),
                                                                                 .Out1_vEnd(Pixel_Control_Bus_Creator_out1_vEnd),
                                                                                 .Out1_valid(Pixel_Control_Bus_Creator_out1_valid)
                                                                                 );

  assign busOut_hStart = Pixel_Control_Bus_Creator_out1_hStart;

  assign busOut_hEnd = Pixel_Control_Bus_Creator_out1_hEnd;

  assign busOut_vStart = Pixel_Control_Bus_Creator_out1_vStart;

  assign busOut_vEnd = Pixel_Control_Bus_Creator_out1_vEnd;

  assign busOut_valid = Pixel_Control_Bus_Creator_out1_valid;

endmodule  // SGBMHDLAl_ip_src_pixelBusGenerator_block6

