// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\SGBMDisparity\SGBMHDLAl_ip_src_Pixel_Control_Bus_Creator.v
// Created: 2021-04-19 19:46:09
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SGBMHDLAl_ip_src_Pixel_Control_Bus_Creator
// Source Path: SGBMDisparity/SGBMHDLAlgorithm/Output/pixelBusGenerator/Pixel Control Bus Creator
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SGBMHDLAl_ip_src_Pixel_Control_Bus_Creator
          (In1,
           In2,
           In3,
           In4,
           In5,
           Out1_hStart,
           Out1_hEnd,
           Out1_vStart,
           Out1_vEnd,
           Out1_valid);


  input   In1;
  input   In2;
  input   In3;
  input   In4;
  input   In5;
  output  Out1_hStart;
  output  Out1_hEnd;
  output  Out1_vStart;
  output  Out1_vEnd;
  output  Out1_valid;




  assign Out1_hStart = In1;

  assign Out1_hEnd = In2;

  assign Out1_vStart = In3;

  assign Out1_vEnd = In4;

  assign Out1_valid = In5;

endmodule  // SGBMHDLAl_ip_src_Pixel_Control_Bus_Creator

