// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\SGBMDisparity\SGBMHDLAl_ip_src_TopRightToBottomLeft.v
// Created: 2021-04-19 19:46:11
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SGBMHDLAl_ip_src_TopRightToBottomLeft
// Source Path: SGBMDisparity/SGBMHDLAlgorithm/SGBMHDLAlgorithmWorker/DirectionalCost/TopRightToBottomLeft
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SGBMHDLAl_ip_src_TopRightToBottomLeft
          (clk,
           reset,
           enb,
           matchCostIn_0,
           matchCostIn_1,
           matchCostIn_2,
           matchCostIn_3,
           matchCostIn_4,
           matchCostIn_5,
           matchCostIn_6,
           matchCostIn_7,
           matchCostIn_8,
           matchCostIn_9,
           matchCostIn_10,
           matchCostIn_11,
           matchCostIn_12,
           matchCostIn_13,
           matchCostIn_14,
           matchCostIn_15,
           busIn_vStart,
           busIn_valid,
           trblOut_0,
           trblOut_1,
           trblOut_2,
           trblOut_3,
           trblOut_4,
           trblOut_5,
           trblOut_6,
           trblOut_7,
           trblOut_8,
           trblOut_9,
           trblOut_10,
           trblOut_11,
           trblOut_12,
           trblOut_13,
           trblOut_14,
           trblOut_15,
           trblBus_valid);


  input   clk;
  input   reset;
  input   enb;
  input   [4:0] matchCostIn_0;  // ufix5
  input   [4:0] matchCostIn_1;  // ufix5
  input   [4:0] matchCostIn_2;  // ufix5
  input   [4:0] matchCostIn_3;  // ufix5
  input   [4:0] matchCostIn_4;  // ufix5
  input   [4:0] matchCostIn_5;  // ufix5
  input   [4:0] matchCostIn_6;  // ufix5
  input   [4:0] matchCostIn_7;  // ufix5
  input   [4:0] matchCostIn_8;  // ufix5
  input   [4:0] matchCostIn_9;  // ufix5
  input   [4:0] matchCostIn_10;  // ufix5
  input   [4:0] matchCostIn_11;  // ufix5
  input   [4:0] matchCostIn_12;  // ufix5
  input   [4:0] matchCostIn_13;  // ufix5
  input   [4:0] matchCostIn_14;  // ufix5
  input   [4:0] matchCostIn_15;  // ufix5
  input   busIn_vStart;
  input   busIn_valid;
  output  signed [9:0] trblOut_0;  // sfix10
  output  signed [9:0] trblOut_1;  // sfix10
  output  signed [9:0] trblOut_2;  // sfix10
  output  signed [9:0] trblOut_3;  // sfix10
  output  signed [9:0] trblOut_4;  // sfix10
  output  signed [9:0] trblOut_5;  // sfix10
  output  signed [9:0] trblOut_6;  // sfix10
  output  signed [9:0] trblOut_7;  // sfix10
  output  signed [9:0] trblOut_8;  // sfix10
  output  signed [9:0] trblOut_9;  // sfix10
  output  signed [9:0] trblOut_10;  // sfix10
  output  signed [9:0] trblOut_11;  // sfix10
  output  signed [9:0] trblOut_12;  // sfix10
  output  signed [9:0] trblOut_13;  // sfix10
  output  signed [9:0] trblOut_14;  // sfix10
  output  signed [9:0] trblOut_15;  // sfix10
  output  trblBus_valid;


  wire valid;
  reg  Delay_out1;
  wire vStart;
  reg [9:0] HDL_Counter_out1;  // ufix10
  wire Compare_To_Constant_out1;
  wire Logical_Operator2_out1;
  wire [4:0] matchCostIn [0:15];  // ufix5 [16]
  reg [4:0] Delay2_out1 [0:15];  // ufix5 [16]
  wire signed [9:0] trblSubsystem_out1_0;  // sfix10
  wire signed [9:0] trblSubsystem_out1_1;  // sfix10
  wire signed [9:0] trblSubsystem_out1_2;  // sfix10
  wire signed [9:0] trblSubsystem_out1_3;  // sfix10
  wire signed [9:0] trblSubsystem_out1_4;  // sfix10
  wire signed [9:0] trblSubsystem_out1_5;  // sfix10
  wire signed [9:0] trblSubsystem_out1_6;  // sfix10
  wire signed [9:0] trblSubsystem_out1_7;  // sfix10
  wire signed [9:0] trblSubsystem_out1_8;  // sfix10
  wire signed [9:0] trblSubsystem_out1_9;  // sfix10
  wire signed [9:0] trblSubsystem_out1_10;  // sfix10
  wire signed [9:0] trblSubsystem_out1_11;  // sfix10
  wire signed [9:0] trblSubsystem_out1_12;  // sfix10
  wire signed [9:0] trblSubsystem_out1_13;  // sfix10
  wire signed [9:0] trblSubsystem_out1_14;  // sfix10
  wire signed [9:0] trblSubsystem_out1_15;  // sfix10
  reg  Delay1_out1_valid;


  assign valid = busIn_valid;

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay_out1 <= valid;
        end
      end
    end



  assign vStart = busIn_vStart;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 623
  always @(posedge clk or posedge reset)
    begin : HDL_Counter_process
      if (reset == 1'b1) begin
        HDL_Counter_out1 <= 10'b0000000000;
      end
      else begin
        if (enb) begin
          if (vStart == 1'b1) begin
            HDL_Counter_out1 <= 10'b0000000000;
          end
          else if (Delay_out1 == 1'b1) begin
            if (HDL_Counter_out1 >= 10'b1001101111) begin
              HDL_Counter_out1 <= 10'b0000000000;
            end
            else begin
              HDL_Counter_out1 <= HDL_Counter_out1 + 10'b0000000001;
            end
          end
        end
      end
    end



  assign Compare_To_Constant_out1 = HDL_Counter_out1 > 10'b0000000000;



  assign Logical_Operator2_out1 = Delay_out1 & Compare_To_Constant_out1;



  assign matchCostIn[0] = matchCostIn_0;
  assign matchCostIn[1] = matchCostIn_1;
  assign matchCostIn[2] = matchCostIn_2;
  assign matchCostIn[3] = matchCostIn_3;
  assign matchCostIn[4] = matchCostIn_4;
  assign matchCostIn[5] = matchCostIn_5;
  assign matchCostIn[6] = matchCostIn_6;
  assign matchCostIn[7] = matchCostIn_7;
  assign matchCostIn[8] = matchCostIn_8;
  assign matchCostIn[9] = matchCostIn_9;
  assign matchCostIn[10] = matchCostIn_10;
  assign matchCostIn[11] = matchCostIn_11;
  assign matchCostIn[12] = matchCostIn_12;
  assign matchCostIn[13] = matchCostIn_13;
  assign matchCostIn[14] = matchCostIn_14;
  assign matchCostIn[15] = matchCostIn_15;

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1[0] <= 5'b00000;
        Delay2_out1[1] <= 5'b00000;
        Delay2_out1[2] <= 5'b00000;
        Delay2_out1[3] <= 5'b00000;
        Delay2_out1[4] <= 5'b00000;
        Delay2_out1[5] <= 5'b00000;
        Delay2_out1[6] <= 5'b00000;
        Delay2_out1[7] <= 5'b00000;
        Delay2_out1[8] <= 5'b00000;
        Delay2_out1[9] <= 5'b00000;
        Delay2_out1[10] <= 5'b00000;
        Delay2_out1[11] <= 5'b00000;
        Delay2_out1[12] <= 5'b00000;
        Delay2_out1[13] <= 5'b00000;
        Delay2_out1[14] <= 5'b00000;
        Delay2_out1[15] <= 5'b00000;
      end
      else begin
        if (enb) begin
          Delay2_out1[0] <= matchCostIn[0];
          Delay2_out1[1] <= matchCostIn[1];
          Delay2_out1[2] <= matchCostIn[2];
          Delay2_out1[3] <= matchCostIn[3];
          Delay2_out1[4] <= matchCostIn[4];
          Delay2_out1[5] <= matchCostIn[5];
          Delay2_out1[6] <= matchCostIn[6];
          Delay2_out1[7] <= matchCostIn[7];
          Delay2_out1[8] <= matchCostIn[8];
          Delay2_out1[9] <= matchCostIn[9];
          Delay2_out1[10] <= matchCostIn[10];
          Delay2_out1[11] <= matchCostIn[11];
          Delay2_out1[12] <= matchCostIn[12];
          Delay2_out1[13] <= matchCostIn[13];
          Delay2_out1[14] <= matchCostIn[14];
          Delay2_out1[15] <= matchCostIn[15];
        end
      end
    end



  SGBMHDLAl_ip_src_trblSubsystem u_trblSubsystem (.clk(clk),
                                                  .reset(reset),
                                                  .enb(enb),
                                                  .enable(Logical_Operator2_out1),
                                                  .matchCostIn_0(Delay2_out1[0]),  // ufix5
                                                  .matchCostIn_1(Delay2_out1[1]),  // ufix5
                                                  .matchCostIn_2(Delay2_out1[2]),  // ufix5
                                                  .matchCostIn_3(Delay2_out1[3]),  // ufix5
                                                  .matchCostIn_4(Delay2_out1[4]),  // ufix5
                                                  .matchCostIn_5(Delay2_out1[5]),  // ufix5
                                                  .matchCostIn_6(Delay2_out1[6]),  // ufix5
                                                  .matchCostIn_7(Delay2_out1[7]),  // ufix5
                                                  .matchCostIn_8(Delay2_out1[8]),  // ufix5
                                                  .matchCostIn_9(Delay2_out1[9]),  // ufix5
                                                  .matchCostIn_10(Delay2_out1[10]),  // ufix5
                                                  .matchCostIn_11(Delay2_out1[11]),  // ufix5
                                                  .matchCostIn_12(Delay2_out1[12]),  // ufix5
                                                  .matchCostIn_13(Delay2_out1[13]),  // ufix5
                                                  .matchCostIn_14(Delay2_out1[14]),  // ufix5
                                                  .matchCostIn_15(Delay2_out1[15]),  // ufix5
                                                  .Enable_1(Delay_out1),
                                                  .trblCost_0(trblSubsystem_out1_0),  // sfix10
                                                  .trblCost_1(trblSubsystem_out1_1),  // sfix10
                                                  .trblCost_2(trblSubsystem_out1_2),  // sfix10
                                                  .trblCost_3(trblSubsystem_out1_3),  // sfix10
                                                  .trblCost_4(trblSubsystem_out1_4),  // sfix10
                                                  .trblCost_5(trblSubsystem_out1_5),  // sfix10
                                                  .trblCost_6(trblSubsystem_out1_6),  // sfix10
                                                  .trblCost_7(trblSubsystem_out1_7),  // sfix10
                                                  .trblCost_8(trblSubsystem_out1_8),  // sfix10
                                                  .trblCost_9(trblSubsystem_out1_9),  // sfix10
                                                  .trblCost_10(trblSubsystem_out1_10),  // sfix10
                                                  .trblCost_11(trblSubsystem_out1_11),  // sfix10
                                                  .trblCost_12(trblSubsystem_out1_12),  // sfix10
                                                  .trblCost_13(trblSubsystem_out1_13),  // sfix10
                                                  .trblCost_14(trblSubsystem_out1_14),  // sfix10
                                                  .trblCost_15(trblSubsystem_out1_15)  // sfix10
                                                  );

  assign trblOut_0 = trblSubsystem_out1_0;

  assign trblOut_1 = trblSubsystem_out1_1;

  assign trblOut_2 = trblSubsystem_out1_2;

  assign trblOut_3 = trblSubsystem_out1_3;

  assign trblOut_4 = trblSubsystem_out1_4;

  assign trblOut_5 = trblSubsystem_out1_5;

  assign trblOut_6 = trblSubsystem_out1_6;

  assign trblOut_7 = trblSubsystem_out1_7;

  assign trblOut_8 = trblSubsystem_out1_8;

  assign trblOut_9 = trblSubsystem_out1_9;

  assign trblOut_10 = trblSubsystem_out1_10;

  assign trblOut_11 = trblSubsystem_out1_11;

  assign trblOut_12 = trblSubsystem_out1_12;

  assign trblOut_13 = trblSubsystem_out1_13;

  assign trblOut_14 = trblSubsystem_out1_14;

  assign trblOut_15 = trblSubsystem_out1_15;

  always @(posedge clk or posedge reset)
    begin : c_4_process
      if (reset == 1'b1) begin
        Delay1_out1_valid <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay1_out1_valid <= busIn_valid;
        end
      end
    end



  assign trblBus_valid = Delay1_out1_valid;

endmodule  // SGBMHDLAl_ip_src_TopRightToBottomLeft

