// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\SGBMDisparity\SGBMHDLAl_ip_src_pixelBusGenerator_block.v
// Created: 2021-04-19 19:46:09
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SGBMHDLAl_ip_src_pixelBusGenerator_block
// Source Path: SGBMDisparity/SGBMHDLAlgorithm/SGBMHDLAlgorithmWorker/DirectionalCost/RightToLeft/pixelBusGenerator
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SGBMHDLAl_ip_src_pixelBusGenerator_block
          (clk,
           reset,
           enb,
           validIn,
           busOut_valid);


  input   clk;
  input   reset;
  input   enb;
  input   validIn;
  output  busOut_valid;


  wire Pixel_Control_Bus_Creator_out1_valid;


  SGBMHDLAl_ip_src_Pixel_Control_Bus_Creator_block u_Pixel_Control_Bus_Creator (.In5(validIn),
                                                                                .Out1_valid(Pixel_Control_Bus_Creator_out1_valid)
                                                                                );

  assign busOut_valid = Pixel_Control_Bus_Creator_out1_valid;




endmodule  // SGBMHDLAl_ip_src_pixelBusGenerator_block

