// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\SGBMDisparity\SGBMHDLAl_ip_src_For_Each_Subsystem_block1.v
// Created: 2021-04-19 19:46:09
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SGBMHDLAl_ip_src_For_Each_Subsystem_block1
// Source Path: SGBMDisparity/SGBMHDLAlgorithm/SGBMHDLAlgorithmWorker/DirectionalCost/TopLeftToBottomRight/tlbrSubsystem/For 
// Each Subsyste
// Hierarchy Level: 5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SGBMHDLAl_ip_src_For_Each_Subsystem_block1
          (Out1);


  output  Out1;


  wire Constant2_out1;


  assign Constant2_out1 = 1'b0;



  assign Out1 = Constant2_out1;

endmodule  // SGBMHDLAl_ip_src_For_Each_Subsystem_block1

