// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\SGBMDisparity\SGBMHDLAl_ip_src_Pixel_Control_Bus_Creator_block7.v
// Created: 2021-04-19 19:46:15
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SGBMHDLAl_ip_src_Pixel_Control_Bus_Creator_block7
// Source Path: SGBMDisparity/SGBMHDLAlgorithm/SGBMHDLAlgorithmWorker/PostProcessing/pixelBusGenerator/Pixel Control 
// Bus Creato
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SGBMHDLAl_ip_src_Pixel_Control_Bus_Creator_block7
          (In5,
           Out1_valid);


  input   In5;
  output  Out1_valid;




  assign Out1_valid = In5;

endmodule  // SGBMHDLAl_ip_src_Pixel_Control_Bus_Creator_block7

