// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\CornerDetection\Harris_HW_ip_src_Vertical_Padding_Counter_block3.v
// Created: 2020-01-15 11:28:57
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Harris_HW_ip_src_Vertical_Padding_Counter_block3
// Source Path: CornerDetection/Harris_HW/HDL Corner Algorithm/GaussianGyGx/LineBuffer/Vertical Padding Counter
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Harris_HW_ip_src_Vertical_Padding_Counter_block3
          (clk,
           reset,
           enb,
           frameEnd,
           unloading,
           running,
           lineStart,
           VCount);


  input   clk;
  input   reset;
  input   enb;
  input   frameEnd;
  input   unloading;
  input   running;
  input   lineStart;
  output  [9:0] VCount;  // ufix10


  wire runningStart;
  wire unloadingStart;
  reg [9:0] VerticalPadCounter;  // ufix10
  wire prePad;
  wire runCountEn;
  wire verCountEn;


  assign runningStart = running & lineStart;



  assign unloadingStart = unloading & lineStart;



  assign prePad = VerticalPadCounter < 10'b0000000010;



  assign runCountEn = runningStart & prePad;



  assign verCountEn = runCountEn | unloadingStart;



  // Free running, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  always @(posedge clk or posedge reset)
    begin : Vertical_Counter_process
      if (reset == 1'b1) begin
        VerticalPadCounter <= 10'b0000000000;
      end
      else begin
        if (enb) begin
          if (frameEnd == 1'b1) begin
            VerticalPadCounter <= 10'b0000000000;
          end
          else if (verCountEn == 1'b1) begin
            VerticalPadCounter <= VerticalPadCounter + 10'b0000000001;
          end
        end
      end
    end



  assign VCount = VerticalPadCounter;

endmodule  // Harris_HW_ip_src_Vertical_Padding_Counter_block3

