// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\CornerDetection\Harris_HW_ip_src_Gradients.v
// Created: 2020-01-15 11:28:57
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Harris_HW_ip_src_Gradients
// Source Path: CornerDetection/Harris_HW/HDL Corner Algorithm/Gradients
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Harris_HW_ip_src_Gradients
          (clk,
           reset,
           enb,
           pixel,
           ctrl_hStart,
           ctrl_hEnd,
           ctrl_vStart,
           ctrl_vEnd,
           ctrl_valid,
           GradY,
           GradX,
           ctrlOut_hStart,
           ctrlOut_hEnd,
           ctrlOut_vStart,
           ctrlOut_vEnd,
           ctrlOut_valid);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] pixel;  // uint8
  input   ctrl_hStart;
  input   ctrl_hEnd;
  input   ctrl_vStart;
  input   ctrl_vEnd;
  input   ctrl_valid;
  output  signed [8:0] GradY;  // sfix9
  output  signed [8:0] GradX;  // sfix9
  output  ctrlOut_hStart;
  output  ctrlOut_hEnd;
  output  ctrlOut_vStart;
  output  ctrlOut_vEnd;
  output  ctrlOut_valid;


  wire signed [8:0] Grady_out1;  // sfix9
  wire Grady_out2_hStart;
  wire Grady_out2_hEnd;
  wire Grady_out2_vStart;
  wire Grady_out2_vEnd;
  wire Grady_out2_valid;
  wire signed [8:0] Gradx_out1;  // sfix9
  wire Gradx_out2_hStart;
  wire Gradx_out2_hEnd;
  wire Gradx_out2_vStart;
  wire Gradx_out2_vEnd;
  wire Gradx_out2_valid;


  Harris_HW_ip_src_Grady u_Grady (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .in0(pixel),  // uint8
                                  .in1_hStart(ctrl_hStart),
                                  .in1_hEnd(ctrl_hEnd),
                                  .in1_vStart(ctrl_vStart),
                                  .in1_vEnd(ctrl_vEnd),
                                  .in1_valid(ctrl_valid),
                                  .out0(Grady_out1),  // sfix9
                                  .out1_hStart(Grady_out2_hStart),
                                  .out1_hEnd(Grady_out2_hEnd),
                                  .out1_vStart(Grady_out2_vStart),
                                  .out1_vEnd(Grady_out2_vEnd),
                                  .out1_valid(Grady_out2_valid)
                                  );

  assign GradY = Grady_out1;

  Harris_HW_ip_src_Gradx u_Gradx (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .in0(pixel),  // uint8
                                  .in1_hStart(ctrl_hStart),
                                  .in1_hEnd(ctrl_hEnd),
                                  .in1_vStart(ctrl_vStart),
                                  .in1_vEnd(ctrl_vEnd),
                                  .in1_valid(ctrl_valid),
                                  .out0(Gradx_out1),  // sfix9
                                  .out1_hStart(Gradx_out2_hStart),
                                  .out1_hEnd(Gradx_out2_hEnd),
                                  .out1_vStart(Gradx_out2_vStart),
                                  .out1_vEnd(Gradx_out2_vEnd),
                                  .out1_valid(Gradx_out2_valid)
                                  );

  assign GradX = Gradx_out1;

  assign ctrlOut_hStart = Gradx_out2_hStart;

  assign ctrlOut_hEnd = Gradx_out2_hEnd;

  assign ctrlOut_vStart = Gradx_out2_vStart;

  assign ctrlOut_vEnd = Gradx_out2_vEnd;

  assign ctrlOut_valid = Gradx_out2_valid;

endmodule  // Harris_HW_ip_src_Gradients

