// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\V1\ContrastS_ip_src_ContrastStretching.v
// Created: 2018-12-04 11:53:13
// 
// Generated by MATLAB 9.3 and HDL Coder 3.11
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ContrastS_ip_src_ContrastStretching
// Source Path: V1/ContrastStretch_HW/ContrastStretching
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ContrastS_ip_src_ContrastStretching
          (clk,
           reset,
           enb,
           pixelIn_0,
           pixelIn_1,
           pixelIn_2,
           ctrlIn_hStart,
           ctrlIn_hEnd,
           ctrlIn_vStart,
           ctrlIn_vEnd,
           ctrlIn_valid,
           pixelOut_0,
           pixelOut_1,
           pixelOut_2,
           ctrlOut_hStart,
           ctrlOut_hEnd,
           ctrlOut_vStart,
           ctrlOut_vEnd,
           ctrlOut_valid);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] pixelIn_0;  // uint8
  input   [7:0] pixelIn_1;  // uint8
  input   [7:0] pixelIn_2;  // uint8
  input   ctrlIn_hStart;
  input   ctrlIn_hEnd;
  input   ctrlIn_vStart;
  input   ctrlIn_vEnd;
  input   ctrlIn_valid;
  output  [7:0] pixelOut_0;  // uint8
  output  [7:0] pixelOut_1;  // uint8
  output  [7:0] pixelOut_2;  // uint8
  output  ctrlOut_hStart;
  output  ctrlOut_hEnd;
  output  ctrlOut_vStart;
  output  ctrlOut_vEnd;
  output  ctrlOut_valid;

  wire [7:0] Color_Space_Converter_out1;  // uint8
  wire Color_Space_Converter_out2_hStart;
  wire Color_Space_Converter_out2_hEnd;
  wire Color_Space_Converter_out2_vStart;
  wire Color_Space_Converter_out2_vEnd;
  wire Color_Space_Converter_out2_valid;
  wire vStart;
  wire valid;
  wire Delay2_ctrl_const_out;
  reg  Delay2_ctrl_delay_out;
  wire [7:0] Delay2_Initial_Val_out;  // uint8
  wire Delay4_ctrl_const_out;
  reg  Delay4_ctrl_delay_out;
  wire [7:0] Delay4_Initial_Val_out;  // uint8
  wire [7:0] next_high;  // uint8
  reg [7:0] Delay4_out;  // uint8
  wire [7:0] Delay4_out1;  // uint8
  wire [19:0] next_high_ctr;  // ufix20
  reg [19:0] Delay3_out1;  // ufix20
  wire [7:0] next_low;  // uint8
  reg [7:0] Delay2_out;  // uint8
  wire [7:0] Delay2_out1;  // uint8
  wire [19:0] next_low_ctr;  // ufix20
  reg [19:0] Delay1_out1;  // ufix20
  wire [17:0] out1;  // ufix18
  wire [7:0] out2;  // uint8
  reg [17:0] out1_1;  // ufix18
  wire [7:0] alpha1_D_Lookup_Table_k;  // ufix8
  wire signed [15:0] alpha1_D_Lookup_Table_1 [0:254];  // sfix16_En15 [255]
  wire signed [15:0] alpha1_D_Lookup_Table_out1;  // sfix16_En15
  reg signed [15:0] alpha1_D_Lookup_Table_out1_1;  // sfix16_En15
  wire signed [18:0] Divide_cast;  // sfix19
  wire signed [34:0] Divide_mul_temp;  // sfix35_En15
  wire signed [33:0] Divide_out1;  // sfix34_En15
  wire [7:0] Data_Type_Conversion_out1;  // uint8

  initial begin
    alpha1_D_Lookup_Table_out1_1 = 16'sb0000000000000000;
  end

  ContrastS_ip_src_Color_Space_Converter u_Color_Space_Converter (.clk(clk),
                                                                  .reset(reset),
                                                                  .enb(enb),
                                                                  .in0_0(pixelIn_0),  // uint8
                                                                  .in0_1(pixelIn_1),  // uint8
                                                                  .in0_2(pixelIn_2),  // uint8
                                                                  .in1_hStart(ctrlIn_hStart),
                                                                  .in1_hEnd(ctrlIn_hEnd),
                                                                  .in1_vStart(ctrlIn_vStart),
                                                                  .in1_vEnd(ctrlIn_vEnd),
                                                                  .in1_valid(ctrlIn_valid),
                                                                  .out0(Color_Space_Converter_out1),  // uint8
                                                                  .out1_hStart(Color_Space_Converter_out2_hStart),
                                                                  .out1_hEnd(Color_Space_Converter_out2_hEnd),
                                                                  .out1_vStart(Color_Space_Converter_out2_vStart),
                                                                  .out1_vEnd(Color_Space_Converter_out2_vEnd),
                                                                  .out1_valid(Color_Space_Converter_out2_valid)
                                                                  );

  assign vStart = Color_Space_Converter_out2_vStart;

  assign valid = Color_Space_Converter_out2_valid;

  assign Delay2_ctrl_const_out = 1'b1;



  always @(posedge clk or posedge reset)
    begin : Delay2_ctrl_delay_process
      if (reset == 1'b1) begin
        Delay2_ctrl_delay_out <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay2_ctrl_delay_out <= Delay2_ctrl_const_out;
        end
      end
    end



  assign Delay2_Initial_Val_out = 8'b00001010;



  assign Delay4_ctrl_const_out = 1'b1;



  always @(posedge clk or posedge reset)
    begin : Delay4_ctrl_delay_process
      if (reset == 1'b1) begin
        Delay4_ctrl_delay_out <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay4_ctrl_delay_out <= Delay4_ctrl_const_out;
        end
      end
    end



  assign Delay4_Initial_Val_out = 8'b11111111;



  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay4_out <= next_high;
        end
      end
    end



  assign Delay4_out1 = (Delay4_ctrl_delay_out == 1'b0 ? Delay4_Initial_Val_out :
              Delay4_out);



  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 20'b00000000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= next_high_ctr;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay2_out <= next_low;
        end
      end
    end



  assign Delay2_out1 = (Delay2_ctrl_delay_out == 1'b0 ? Delay2_Initial_Val_out :
              Delay2_out);



  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 20'b00000000000000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= next_low_ctr;
        end
      end
    end



  ContrastS_ip_src_MATLAB_Function u_MATLAB_Function (.in(Color_Space_Converter_out1),  // uint8
                                                      .vstart(vStart),
                                                      .valid(valid),
                                                      .curr_low_ctr(Delay1_out1),  // ufix20
                                                      .curr_low(Delay2_out1),  // uint8
                                                      .curr_high_ctr(Delay3_out1),  // ufix20
                                                      .curr_high(Delay4_out1),  // uint8
                                                      .out1(out1),  // ufix18
                                                      .out2(out2),  // uint8
                                                      .next_low_ctr(next_low_ctr),  // ufix20
                                                      .next_low(next_low),  // uint8
                                                      .next_high_ctr(next_high_ctr),  // ufix20
                                                      .next_high(next_high)  // uint8
                                                      );

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        out1_1 <= 18'b000000000000000000;
      end
      else begin
        if (enb) begin
          out1_1 <= out1;
        end
      end
    end



  assign alpha1_D_Lookup_Table_1[0] = 16'sb0111111111111111;
  assign alpha1_D_Lookup_Table_1[1] = 16'sb0100000000000000;
  assign alpha1_D_Lookup_Table_1[2] = 16'sb0010101010101011;
  assign alpha1_D_Lookup_Table_1[3] = 16'sb0010000000000000;
  assign alpha1_D_Lookup_Table_1[4] = 16'sb0001100110011010;
  assign alpha1_D_Lookup_Table_1[5] = 16'sb0001010101010101;
  assign alpha1_D_Lookup_Table_1[6] = 16'sb0001001001001001;
  assign alpha1_D_Lookup_Table_1[7] = 16'sb0001000000000000;
  assign alpha1_D_Lookup_Table_1[8] = 16'sb0000111000111001;
  assign alpha1_D_Lookup_Table_1[9] = 16'sb0000110011001101;
  assign alpha1_D_Lookup_Table_1[10] = 16'sb0000101110100011;
  assign alpha1_D_Lookup_Table_1[11] = 16'sb0000101010101011;
  assign alpha1_D_Lookup_Table_1[12] = 16'sb0000100111011001;
  assign alpha1_D_Lookup_Table_1[13] = 16'sb0000100100100101;
  assign alpha1_D_Lookup_Table_1[14] = 16'sb0000100010001001;
  assign alpha1_D_Lookup_Table_1[15] = 16'sb0000100000000000;
  assign alpha1_D_Lookup_Table_1[16] = 16'sb0000011110001000;
  assign alpha1_D_Lookup_Table_1[17] = 16'sb0000011100011100;
  assign alpha1_D_Lookup_Table_1[18] = 16'sb0000011010111101;
  assign alpha1_D_Lookup_Table_1[19] = 16'sb0000011001100110;
  assign alpha1_D_Lookup_Table_1[20] = 16'sb0000011000011000;
  assign alpha1_D_Lookup_Table_1[21] = 16'sb0000010111010001;
  assign alpha1_D_Lookup_Table_1[22] = 16'sb0000010110010001;
  assign alpha1_D_Lookup_Table_1[23] = 16'sb0000010101010101;
  assign alpha1_D_Lookup_Table_1[24] = 16'sb0000010100011111;
  assign alpha1_D_Lookup_Table_1[25] = 16'sb0000010011101100;
  assign alpha1_D_Lookup_Table_1[26] = 16'sb0000010010111110;
  assign alpha1_D_Lookup_Table_1[27] = 16'sb0000010010010010;
  assign alpha1_D_Lookup_Table_1[28] = 16'sb0000010001101010;
  assign alpha1_D_Lookup_Table_1[29] = 16'sb0000010001000100;
  assign alpha1_D_Lookup_Table_1[30] = 16'sb0000010000100001;
  assign alpha1_D_Lookup_Table_1[31] = 16'sb0000010000000000;
  assign alpha1_D_Lookup_Table_1[32] = 16'sb0000001111100001;
  assign alpha1_D_Lookup_Table_1[33] = 16'sb0000001111000100;
  assign alpha1_D_Lookup_Table_1[34] = 16'sb0000001110101000;
  assign alpha1_D_Lookup_Table_1[35] = 16'sb0000001110001110;
  assign alpha1_D_Lookup_Table_1[36] = 16'sb0000001101110110;
  assign alpha1_D_Lookup_Table_1[37] = 16'sb0000001101011110;
  assign alpha1_D_Lookup_Table_1[38] = 16'sb0000001101001000;
  assign alpha1_D_Lookup_Table_1[39] = 16'sb0000001100110011;
  assign alpha1_D_Lookup_Table_1[40] = 16'sb0000001100011111;
  assign alpha1_D_Lookup_Table_1[41] = 16'sb0000001100001100;
  assign alpha1_D_Lookup_Table_1[42] = 16'sb0000001011111010;
  assign alpha1_D_Lookup_Table_1[43] = 16'sb0000001011101001;
  assign alpha1_D_Lookup_Table_1[44] = 16'sb0000001011011000;
  assign alpha1_D_Lookup_Table_1[45] = 16'sb0000001011001000;
  assign alpha1_D_Lookup_Table_1[46] = 16'sb0000001010111001;
  assign alpha1_D_Lookup_Table_1[47] = 16'sb0000001010101011;
  assign alpha1_D_Lookup_Table_1[48] = 16'sb0000001010011101;
  assign alpha1_D_Lookup_Table_1[49] = 16'sb0000001010001111;
  assign alpha1_D_Lookup_Table_1[50] = 16'sb0000001010000011;
  assign alpha1_D_Lookup_Table_1[51] = 16'sb0000001001110110;
  assign alpha1_D_Lookup_Table_1[52] = 16'sb0000001001101010;
  assign alpha1_D_Lookup_Table_1[53] = 16'sb0000001001011111;
  assign alpha1_D_Lookup_Table_1[54] = 16'sb0000001001010100;
  assign alpha1_D_Lookup_Table_1[55] = 16'sb0000001001001001;
  assign alpha1_D_Lookup_Table_1[56] = 16'sb0000001000111111;
  assign alpha1_D_Lookup_Table_1[57] = 16'sb0000001000110101;
  assign alpha1_D_Lookup_Table_1[58] = 16'sb0000001000101011;
  assign alpha1_D_Lookup_Table_1[59] = 16'sb0000001000100010;
  assign alpha1_D_Lookup_Table_1[60] = 16'sb0000001000011001;
  assign alpha1_D_Lookup_Table_1[61] = 16'sb0000001000010001;
  assign alpha1_D_Lookup_Table_1[62] = 16'sb0000001000001000;
  assign alpha1_D_Lookup_Table_1[63] = 16'sb0000001000000000;
  assign alpha1_D_Lookup_Table_1[64] = 16'sb0000000111111000;
  assign alpha1_D_Lookup_Table_1[65] = 16'sb0000000111110000;
  assign alpha1_D_Lookup_Table_1[66] = 16'sb0000000111101001;
  assign alpha1_D_Lookup_Table_1[67] = 16'sb0000000111100010;
  assign alpha1_D_Lookup_Table_1[68] = 16'sb0000000111011011;
  assign alpha1_D_Lookup_Table_1[69] = 16'sb0000000111010100;
  assign alpha1_D_Lookup_Table_1[70] = 16'sb0000000111001110;
  assign alpha1_D_Lookup_Table_1[71] = 16'sb0000000111000111;
  assign alpha1_D_Lookup_Table_1[72] = 16'sb0000000111000001;
  assign alpha1_D_Lookup_Table_1[73] = 16'sb0000000110111011;
  assign alpha1_D_Lookup_Table_1[74] = 16'sb0000000110110101;
  assign alpha1_D_Lookup_Table_1[75] = 16'sb0000000110101111;
  assign alpha1_D_Lookup_Table_1[76] = 16'sb0000000110101010;
  assign alpha1_D_Lookup_Table_1[77] = 16'sb0000000110100100;
  assign alpha1_D_Lookup_Table_1[78] = 16'sb0000000110011111;
  assign alpha1_D_Lookup_Table_1[79] = 16'sb0000000110011010;
  assign alpha1_D_Lookup_Table_1[80] = 16'sb0000000110010101;
  assign alpha1_D_Lookup_Table_1[81] = 16'sb0000000110010000;
  assign alpha1_D_Lookup_Table_1[82] = 16'sb0000000110001011;
  assign alpha1_D_Lookup_Table_1[83] = 16'sb0000000110000110;
  assign alpha1_D_Lookup_Table_1[84] = 16'sb0000000110000010;
  assign alpha1_D_Lookup_Table_1[85] = 16'sb0000000101111101;
  assign alpha1_D_Lookup_Table_1[86] = 16'sb0000000101111001;
  assign alpha1_D_Lookup_Table_1[87] = 16'sb0000000101110100;
  assign alpha1_D_Lookup_Table_1[88] = 16'sb0000000101110000;
  assign alpha1_D_Lookup_Table_1[89] = 16'sb0000000101101100;
  assign alpha1_D_Lookup_Table_1[90] = 16'sb0000000101101000;
  assign alpha1_D_Lookup_Table_1[91] = 16'sb0000000101100100;
  assign alpha1_D_Lookup_Table_1[92] = 16'sb0000000101100000;
  assign alpha1_D_Lookup_Table_1[93] = 16'sb0000000101011101;
  assign alpha1_D_Lookup_Table_1[94] = 16'sb0000000101011001;
  assign alpha1_D_Lookup_Table_1[95] = 16'sb0000000101010101;
  assign alpha1_D_Lookup_Table_1[96] = 16'sb0000000101010010;
  assign alpha1_D_Lookup_Table_1[97] = 16'sb0000000101001110;
  assign alpha1_D_Lookup_Table_1[98] = 16'sb0000000101001011;
  assign alpha1_D_Lookup_Table_1[99] = 16'sb0000000101001000;
  assign alpha1_D_Lookup_Table_1[100] = 16'sb0000000101000100;
  assign alpha1_D_Lookup_Table_1[101] = 16'sb0000000101000001;
  assign alpha1_D_Lookup_Table_1[102] = 16'sb0000000100111110;
  assign alpha1_D_Lookup_Table_1[103] = 16'sb0000000100111011;
  assign alpha1_D_Lookup_Table_1[104] = 16'sb0000000100111000;
  assign alpha1_D_Lookup_Table_1[105] = 16'sb0000000100110101;
  assign alpha1_D_Lookup_Table_1[106] = 16'sb0000000100110010;
  assign alpha1_D_Lookup_Table_1[107] = 16'sb0000000100101111;
  assign alpha1_D_Lookup_Table_1[108] = 16'sb0000000100101101;
  assign alpha1_D_Lookup_Table_1[109] = 16'sb0000000100101010;
  assign alpha1_D_Lookup_Table_1[110] = 16'sb0000000100100111;
  assign alpha1_D_Lookup_Table_1[111] = 16'sb0000000100100101;
  assign alpha1_D_Lookup_Table_1[112] = 16'sb0000000100100010;
  assign alpha1_D_Lookup_Table_1[113] = 16'sb0000000100011111;
  assign alpha1_D_Lookup_Table_1[114] = 16'sb0000000100011101;
  assign alpha1_D_Lookup_Table_1[115] = 16'sb0000000100011010;
  assign alpha1_D_Lookup_Table_1[116] = 16'sb0000000100011000;
  assign alpha1_D_Lookup_Table_1[117] = 16'sb0000000100010110;
  assign alpha1_D_Lookup_Table_1[118] = 16'sb0000000100010011;
  assign alpha1_D_Lookup_Table_1[119] = 16'sb0000000100010001;
  assign alpha1_D_Lookup_Table_1[120] = 16'sb0000000100001111;
  assign alpha1_D_Lookup_Table_1[121] = 16'sb0000000100001101;
  assign alpha1_D_Lookup_Table_1[122] = 16'sb0000000100001010;
  assign alpha1_D_Lookup_Table_1[123] = 16'sb0000000100001000;
  assign alpha1_D_Lookup_Table_1[124] = 16'sb0000000100000110;
  assign alpha1_D_Lookup_Table_1[125] = 16'sb0000000100000100;
  assign alpha1_D_Lookup_Table_1[126] = 16'sb0000000100000010;
  assign alpha1_D_Lookup_Table_1[127] = 16'sb0000000100000000;
  assign alpha1_D_Lookup_Table_1[128] = 16'sb0000000011111110;
  assign alpha1_D_Lookup_Table_1[129] = 16'sb0000000011111100;
  assign alpha1_D_Lookup_Table_1[130] = 16'sb0000000011111010;
  assign alpha1_D_Lookup_Table_1[131] = 16'sb0000000011111000;
  assign alpha1_D_Lookup_Table_1[132] = 16'sb0000000011110110;
  assign alpha1_D_Lookup_Table_1[133] = 16'sb0000000011110101;
  assign alpha1_D_Lookup_Table_1[134] = 16'sb0000000011110011;
  assign alpha1_D_Lookup_Table_1[135] = 16'sb0000000011110001;
  assign alpha1_D_Lookup_Table_1[136] = 16'sb0000000011101111;
  assign alpha1_D_Lookup_Table_1[137] = 16'sb0000000011101101;
  assign alpha1_D_Lookup_Table_1[138] = 16'sb0000000011101100;
  assign alpha1_D_Lookup_Table_1[139] = 16'sb0000000011101010;
  assign alpha1_D_Lookup_Table_1[140] = 16'sb0000000011101000;
  assign alpha1_D_Lookup_Table_1[141] = 16'sb0000000011100111;
  assign alpha1_D_Lookup_Table_1[142] = 16'sb0000000011100101;
  assign alpha1_D_Lookup_Table_1[143] = 16'sb0000000011100100;
  assign alpha1_D_Lookup_Table_1[144] = 16'sb0000000011100010;
  assign alpha1_D_Lookup_Table_1[145] = 16'sb0000000011100000;
  assign alpha1_D_Lookup_Table_1[146] = 16'sb0000000011011111;
  assign alpha1_D_Lookup_Table_1[147] = 16'sb0000000011011101;
  assign alpha1_D_Lookup_Table_1[148] = 16'sb0000000011011100;
  assign alpha1_D_Lookup_Table_1[149] = 16'sb0000000011011010;
  assign alpha1_D_Lookup_Table_1[150] = 16'sb0000000011011001;
  assign alpha1_D_Lookup_Table_1[151] = 16'sb0000000011011000;
  assign alpha1_D_Lookup_Table_1[152] = 16'sb0000000011010110;
  assign alpha1_D_Lookup_Table_1[153] = 16'sb0000000011010101;
  assign alpha1_D_Lookup_Table_1[154] = 16'sb0000000011010011;
  assign alpha1_D_Lookup_Table_1[155] = 16'sb0000000011010010;
  assign alpha1_D_Lookup_Table_1[156] = 16'sb0000000011010001;
  assign alpha1_D_Lookup_Table_1[157] = 16'sb0000000011001111;
  assign alpha1_D_Lookup_Table_1[158] = 16'sb0000000011001110;
  assign alpha1_D_Lookup_Table_1[159] = 16'sb0000000011001101;
  assign alpha1_D_Lookup_Table_1[160] = 16'sb0000000011001100;
  assign alpha1_D_Lookup_Table_1[161] = 16'sb0000000011001010;
  assign alpha1_D_Lookup_Table_1[162] = 16'sb0000000011001001;
  assign alpha1_D_Lookup_Table_1[163] = 16'sb0000000011001000;
  assign alpha1_D_Lookup_Table_1[164] = 16'sb0000000011000111;
  assign alpha1_D_Lookup_Table_1[165] = 16'sb0000000011000101;
  assign alpha1_D_Lookup_Table_1[166] = 16'sb0000000011000100;
  assign alpha1_D_Lookup_Table_1[167] = 16'sb0000000011000011;
  assign alpha1_D_Lookup_Table_1[168] = 16'sb0000000011000010;
  assign alpha1_D_Lookup_Table_1[169] = 16'sb0000000011000001;
  assign alpha1_D_Lookup_Table_1[170] = 16'sb0000000011000000;
  assign alpha1_D_Lookup_Table_1[171] = 16'sb0000000010111111;
  assign alpha1_D_Lookup_Table_1[172] = 16'sb0000000010111101;
  assign alpha1_D_Lookup_Table_1[173] = 16'sb0000000010111100;
  assign alpha1_D_Lookup_Table_1[174] = 16'sb0000000010111011;
  assign alpha1_D_Lookup_Table_1[175] = 16'sb0000000010111010;
  assign alpha1_D_Lookup_Table_1[176] = 16'sb0000000010111001;
  assign alpha1_D_Lookup_Table_1[177] = 16'sb0000000010111000;
  assign alpha1_D_Lookup_Table_1[178] = 16'sb0000000010110111;
  assign alpha1_D_Lookup_Table_1[179] = 16'sb0000000010110110;
  assign alpha1_D_Lookup_Table_1[180] = 16'sb0000000010110101;
  assign alpha1_D_Lookup_Table_1[181] = 16'sb0000000010110100;
  assign alpha1_D_Lookup_Table_1[182] = 16'sb0000000010110011;
  assign alpha1_D_Lookup_Table_1[183] = 16'sb0000000010110010;
  assign alpha1_D_Lookup_Table_1[184] = 16'sb0000000010110001;
  assign alpha1_D_Lookup_Table_1[185] = 16'sb0000000010110000;
  assign alpha1_D_Lookup_Table_1[186] = 16'sb0000000010101111;
  assign alpha1_D_Lookup_Table_1[187] = 16'sb0000000010101110;
  assign alpha1_D_Lookup_Table_1[188] = 16'sb0000000010101101;
  assign alpha1_D_Lookup_Table_1[189] = 16'sb0000000010101100;
  assign alpha1_D_Lookup_Table_1[190] = 16'sb0000000010101100;
  assign alpha1_D_Lookup_Table_1[191] = 16'sb0000000010101011;
  assign alpha1_D_Lookup_Table_1[192] = 16'sb0000000010101010;
  assign alpha1_D_Lookup_Table_1[193] = 16'sb0000000010101001;
  assign alpha1_D_Lookup_Table_1[194] = 16'sb0000000010101000;
  assign alpha1_D_Lookup_Table_1[195] = 16'sb0000000010100111;
  assign alpha1_D_Lookup_Table_1[196] = 16'sb0000000010100110;
  assign alpha1_D_Lookup_Table_1[197] = 16'sb0000000010100101;
  assign alpha1_D_Lookup_Table_1[198] = 16'sb0000000010100101;
  assign alpha1_D_Lookup_Table_1[199] = 16'sb0000000010100100;
  assign alpha1_D_Lookup_Table_1[200] = 16'sb0000000010100011;
  assign alpha1_D_Lookup_Table_1[201] = 16'sb0000000010100010;
  assign alpha1_D_Lookup_Table_1[202] = 16'sb0000000010100001;
  assign alpha1_D_Lookup_Table_1[203] = 16'sb0000000010100001;
  assign alpha1_D_Lookup_Table_1[204] = 16'sb0000000010100000;
  assign alpha1_D_Lookup_Table_1[205] = 16'sb0000000010011111;
  assign alpha1_D_Lookup_Table_1[206] = 16'sb0000000010011110;
  assign alpha1_D_Lookup_Table_1[207] = 16'sb0000000010011110;
  assign alpha1_D_Lookup_Table_1[208] = 16'sb0000000010011101;
  assign alpha1_D_Lookup_Table_1[209] = 16'sb0000000010011100;
  assign alpha1_D_Lookup_Table_1[210] = 16'sb0000000010011011;
  assign alpha1_D_Lookup_Table_1[211] = 16'sb0000000010011011;
  assign alpha1_D_Lookup_Table_1[212] = 16'sb0000000010011010;
  assign alpha1_D_Lookup_Table_1[213] = 16'sb0000000010011001;
  assign alpha1_D_Lookup_Table_1[214] = 16'sb0000000010011000;
  assign alpha1_D_Lookup_Table_1[215] = 16'sb0000000010011000;
  assign alpha1_D_Lookup_Table_1[216] = 16'sb0000000010010111;
  assign alpha1_D_Lookup_Table_1[217] = 16'sb0000000010010110;
  assign alpha1_D_Lookup_Table_1[218] = 16'sb0000000010010110;
  assign alpha1_D_Lookup_Table_1[219] = 16'sb0000000010010101;
  assign alpha1_D_Lookup_Table_1[220] = 16'sb0000000010010100;
  assign alpha1_D_Lookup_Table_1[221] = 16'sb0000000010010100;
  assign alpha1_D_Lookup_Table_1[222] = 16'sb0000000010010011;
  assign alpha1_D_Lookup_Table_1[223] = 16'sb0000000010010010;
  assign alpha1_D_Lookup_Table_1[224] = 16'sb0000000010010010;
  assign alpha1_D_Lookup_Table_1[225] = 16'sb0000000010010001;
  assign alpha1_D_Lookup_Table_1[226] = 16'sb0000000010010000;
  assign alpha1_D_Lookup_Table_1[227] = 16'sb0000000010010000;
  assign alpha1_D_Lookup_Table_1[228] = 16'sb0000000010001111;
  assign alpha1_D_Lookup_Table_1[229] = 16'sb0000000010001110;
  assign alpha1_D_Lookup_Table_1[230] = 16'sb0000000010001110;
  assign alpha1_D_Lookup_Table_1[231] = 16'sb0000000010001101;
  assign alpha1_D_Lookup_Table_1[232] = 16'sb0000000010001101;
  assign alpha1_D_Lookup_Table_1[233] = 16'sb0000000010001100;
  assign alpha1_D_Lookup_Table_1[234] = 16'sb0000000010001011;
  assign alpha1_D_Lookup_Table_1[235] = 16'sb0000000010001011;
  assign alpha1_D_Lookup_Table_1[236] = 16'sb0000000010001010;
  assign alpha1_D_Lookup_Table_1[237] = 16'sb0000000010001010;
  assign alpha1_D_Lookup_Table_1[238] = 16'sb0000000010001001;
  assign alpha1_D_Lookup_Table_1[239] = 16'sb0000000010001001;
  assign alpha1_D_Lookup_Table_1[240] = 16'sb0000000010001000;
  assign alpha1_D_Lookup_Table_1[241] = 16'sb0000000010000111;
  assign alpha1_D_Lookup_Table_1[242] = 16'sb0000000010000111;
  assign alpha1_D_Lookup_Table_1[243] = 16'sb0000000010000110;
  assign alpha1_D_Lookup_Table_1[244] = 16'sb0000000010000110;
  assign alpha1_D_Lookup_Table_1[245] = 16'sb0000000010000101;
  assign alpha1_D_Lookup_Table_1[246] = 16'sb0000000010000101;
  assign alpha1_D_Lookup_Table_1[247] = 16'sb0000000010000100;
  assign alpha1_D_Lookup_Table_1[248] = 16'sb0000000010000100;
  assign alpha1_D_Lookup_Table_1[249] = 16'sb0000000010000011;
  assign alpha1_D_Lookup_Table_1[250] = 16'sb0000000010000011;
  assign alpha1_D_Lookup_Table_1[251] = 16'sb0000000010000010;
  assign alpha1_D_Lookup_Table_1[252] = 16'sb0000000010000010;
  assign alpha1_D_Lookup_Table_1[253] = 16'sb0000000010000001;
  assign alpha1_D_Lookup_Table_1[254] = 16'sb0000000010000001;
  assign alpha1_D_Lookup_Table_k = (out2 <= 8'b00000001 ? 8'b00000000 :
              (out2 == 8'b11111111 ? 8'b11111110 :
              out2 - 8'b00000001));
  assign alpha1_D_Lookup_Table_out1 = alpha1_D_Lookup_Table_1[alpha1_D_Lookup_Table_k];



  always @(posedge clk)
    begin : PipelineRegister_process
      if (enb) begin
        alpha1_D_Lookup_Table_out1_1 <= alpha1_D_Lookup_Table_out1;
      end
    end



  assign Divide_cast = {1'b0, out1_1};
  assign Divide_mul_temp = Divide_cast * alpha1_D_Lookup_Table_out1_1;
  assign Divide_out1 = Divide_mul_temp[33:0];



  assign Data_Type_Conversion_out1 = Divide_out1[22:15];



  assign pixelOut_0 = Data_Type_Conversion_out1;

  assign pixelOut_1 = Data_Type_Conversion_out1;

  assign pixelOut_2 = Data_Type_Conversion_out1;

  assign ctrlOut_hStart = Color_Space_Converter_out2_hStart;

  assign ctrlOut_hEnd = Color_Space_Converter_out2_hEnd;

  assign ctrlOut_vStart = Color_Space_Converter_out2_vStart;

  assign ctrlOut_vEnd = Color_Space_Converter_out2_vEnd;

  assign ctrlOut_valid = Color_Space_Converter_out2_valid;




endmodule  // ContrastS_ip_src_ContrastStretching

