-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Disparity_CT\DisparityV0_ip_dut.vhd
-- Created: 2021-04-25 08:29:47
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DisparityV0_ip_dut
-- Source Path: DisparityV0_ip/DisparityV0_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DisparityV0_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        pixelIn                           :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ctrlIn_hStart                     :   IN    std_logic;  -- ufix1
        ctrlIn_hEnd                       :   IN    std_logic;  -- ufix1
        ctrlIn_vStart                     :   IN    std_logic;  -- ufix1
        ctrlIn_vEnd                       :   IN    std_logic;  -- ufix1
        ctrlIn_valid                      :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        pixelOut                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        ctrlOut_hStart                    :   OUT   std_logic;  -- ufix1
        ctrlOut_hEnd                      :   OUT   std_logic;  -- ufix1
        ctrlOut_vStart                    :   OUT   std_logic;  -- ufix1
        ctrlOut_vEnd                      :   OUT   std_logic;  -- ufix1
        ctrlOut_valid                     :   OUT   std_logic  -- ufix1
        );
END DisparityV0_ip_dut;


ARCHITECTURE rtl OF DisparityV0_ip_dut IS

  -- Component Declarations
  COMPONENT DisparityV0_ip_src_DisparityV0
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          pixelIn                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ctrlIn_hStart                   :   IN    std_logic;  -- ufix1
          ctrlIn_hEnd                     :   IN    std_logic;  -- ufix1
          ctrlIn_vStart                   :   IN    std_logic;  -- ufix1
          ctrlIn_vEnd                     :   IN    std_logic;  -- ufix1
          ctrlIn_valid                    :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          pixelOut                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          ctrlOut_hStart                  :   OUT   std_logic;  -- ufix1
          ctrlOut_hEnd                    :   OUT   std_logic;  -- ufix1
          ctrlOut_vStart                  :   OUT   std_logic;  -- ufix1
          ctrlOut_vEnd                    :   OUT   std_logic;  -- ufix1
          ctrlOut_valid                   :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : DisparityV0_ip_src_DisparityV0
    USE ENTITY work.DisparityV0_ip_src_DisparityV0(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL ctrlIn_hStart_sig                : std_logic;  -- ufix1
  SIGNAL ctrlIn_hEnd_sig                  : std_logic;  -- ufix1
  SIGNAL ctrlIn_vStart_sig                : std_logic;  -- ufix1
  SIGNAL ctrlIn_vEnd_sig                  : std_logic;  -- ufix1
  SIGNAL ctrlIn_valid_sig                 : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL pixelOut_sig                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL ctrlOut_hStart_sig               : std_logic;  -- ufix1
  SIGNAL ctrlOut_hEnd_sig                 : std_logic;  -- ufix1
  SIGNAL ctrlOut_vStart_sig               : std_logic;  -- ufix1
  SIGNAL ctrlOut_vEnd_sig                 : std_logic;  -- ufix1
  SIGNAL ctrlOut_valid_sig                : std_logic;  -- ufix1

BEGIN
  u_DisparityV0_ip_src_DisparityV0 : DisparityV0_ip_src_DisparityV0
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              pixelIn => pixelIn,  -- ufix32
              ctrlIn_hStart => ctrlIn_hStart_sig,  -- ufix1
              ctrlIn_hEnd => ctrlIn_hEnd_sig,  -- ufix1
              ctrlIn_vStart => ctrlIn_vStart_sig,  -- ufix1
              ctrlIn_vEnd => ctrlIn_vEnd_sig,  -- ufix1
              ctrlIn_valid => ctrlIn_valid_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              pixelOut => pixelOut_sig,  -- ufix32
              ctrlOut_hStart => ctrlOut_hStart_sig,  -- ufix1
              ctrlOut_hEnd => ctrlOut_hEnd_sig,  -- ufix1
              ctrlOut_vStart => ctrlOut_vStart_sig,  -- ufix1
              ctrlOut_vEnd => ctrlOut_vEnd_sig,  -- ufix1
              ctrlOut_valid => ctrlOut_valid_sig  -- ufix1
              );

  ctrlIn_hStart_sig <= ctrlIn_hStart;

  ctrlIn_hEnd_sig <= ctrlIn_hEnd;

  ctrlIn_vStart_sig <= ctrlIn_vStart;

  ctrlIn_vEnd_sig <= ctrlIn_vEnd;

  ctrlIn_valid_sig <= ctrlIn_valid;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  pixelOut <= pixelOut_sig;

  ctrlOut_hStart <= ctrlOut_hStart_sig;

  ctrlOut_hEnd <= ctrlOut_hEnd_sig;

  ctrlOut_vStart <= ctrlOut_vStart_sig;

  ctrlOut_vEnd <= ctrlOut_vEnd_sig;

  ctrlOut_valid <= ctrlOut_valid_sig;

END rtl;

