// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HSG\HSG_IP_src_unloadLineMask.v
// Created: 2018-10-21 17:42:58
// 
// Generated by MATLAB 9.3 and HDL Coder 3.11
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HSG_IP_src_unloadLineMask
// Source Path: HSG/HSG/Edge Detector/LineBuffer/DataMemory/unloadLineMask
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HSG_IP_src_unloadLineMask
          (islineStart1,
           islineStart2,
           lineMask,
           allNextLineStart);


  input   islineStart1;
  input   islineStart2;
  input   [1:0] lineMask;  // ufix2
  output  allNextLineStart;

  wire lineMaskSlice2;
  wire INIT;
  wire isStart2;


  assign lineMaskSlice2 = lineMask[1];



  assign INIT = 1'b1;



  HSG_IP_src_isLineStart u_isStart (.lineEn(lineMaskSlice2),
                                    .lineIn(islineStart2),
                                    .init(INIT),
                                    .lineStart(isStart2)
                                    );

  assign allNextLineStart = isStart2;

endmodule  // HSG_IP_src_unloadLineMask

